name: Run Playwright Tests

on:
  push:
    branches: [tailwindcss]

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PLAYWRIGHT_GITHUB_TOKEN: ${{ secrets.PLAYWRIGHT_GITHUB_TOKEN }}
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./test-results
